[pytest]
markers =
    unit: marks tests as unit tests
    functional: marks tests as functional tests
    slow: marks tests as slow
    edge_case: marks tests as edge cases
    ui: marks tests that involve UI elements
    integration: marks tests as integration tests
